language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/modules-2/"
  - "$HOME/.gradle/wrapper/"
  timeout: 600
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew properties dumpEnv -Pgradle.publish.key=$FOO -Pgradle.publish.secret=$BAR"
  on:
    # don't deploy from forks; TODO test with PRs
    repo: gosu-lang/gradle-gosu-plugin
    all_branches: true

notifications:
  slack:
    on_success: change
    secure: K3kwtEQQczbwkw+8OeLnjtgVPPzpNfx+5jnn8r6zI7x641TnkDPb5WMZjhEjZqeK/dyG1NOGcpmNU48EhmHtQoZExPxnMB5VvzRvtxaaNWsFEuC5PeQz4xCkNTYDMB3VnGyA5CEBp3yFNx+SOswjNpNSuXnEV8SbcsgPllN/D6WKT9Wh9uBvr9c1YOxQ8BHAGZYelxARj7EzWAgkDxuSQk3bKY1BfKFCDiMe/y3TDm4SHaYWqgsHAvNVLlEhsOGTKi2rl/gniwsKD8LYOLUwF5exRhV5f/i+Qc4D8i6FKRGR/+ncA4ItW/YPui0+b+z8ca7cTvmFIRG5kkN4IFSVz/YR4bYFfvd4KzN3x7EsRijXD2OJQhPHXwPXh8cdwc3vimn2mDLYt4EMW+U2uP50DMKdZdAoktmmOdzCh3m1h6ONcZ6ul2CpJWWvJWfENAb5zJZd55qrOaSDc+t/2WyIYRDqIyuZsOCGKTcEsPUIunG8udvGhfhkcDKz+1fpr8Xazm4kTSdyu1mpvCiJvPDJGeaZGTM+EOiugIEQFO7LdXVGH3I72PduktbSLmBs91C2/8R4/AYpLdK1Ytc0o7UbZ/zIP+jSffxvEJBwTpuNi/se41MRr2NHVun0UFvTfn4hNtoz8xXwSadNqlxf5zF9a0LzwbfIO07VJkba3Es27wE=
