defaults: &defaults
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb
    MAVEN_OPTS: "-Xmx1024m"
  docker:
    - image: circleci/openjdk:11-jdk
version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Compile
          command: ./gradlew compile
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run tests
          command: ./gradlew check
      - store_artifacts:
          path: ~/project/build/reports/tests
      - store_test_results:
          path: ~/project/build/test-results/test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
workflows:
  version: 2
  build_and_test_all_branches:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /rel\/.*/
                - /user\/sv\/.*/
      - test:
          requires:
            - build