defaults: &defaults
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb
    MAVEN_OPTS: "-Xmx1024m"
  docker:
    - image: circleci/openjdk:11-jdk
version: 2.1
parameters:
  run_workflow_release:
    default: false
    type: boolean
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Compile
          command: ./gradlew compileJava compileGroovy
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run tests
          command: ./gradlew check
      - store_artifacts:
          path: ~/project/build/reports/tests
      - store_test_results:
          path: ~/project/build/test-results/test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Prepare and release
          command: ./.circleci/release.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
workflows:
  version: 2
  build_and_test_only:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /rel\/.*/
      - test:
          requires:
            - build
  build_test_release:
    when: << pipeline.parameters.run_workflow_release >>
    jobs:
      - build:
          filters:
            branches:
              only:
                - /rel\/.*/
                - /user\/sv\/.*/
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test-java11
      - release:
          requires:
            - hold